### PR TITLE
Fix bug: false positive warning for typed function calls

### LINKED ISSUE #91: [BUG] false positive for Eventually/Consistently
**Describe the bug**

The following finding is a false positive:

```
test/e2e_node/dra_test.go:129:4: ginkgo-linter: use a function call in Consistently. This actually checks nothing, because Consistently receives the function returned value, instead of function itself, and this value is never changed; consider using `gomega.Consistently(ctx, e2epod.Get).WithArguments(f.ClientSet, pod).WithTimeout(podInPendingStateTimeout).Should(e2epod.BeInPhase(v1.PodPending),
	"Pod should be in Pending state as resource preparation time outed")` instead (ginkgolinter)
			gomega.Consistently(ctx, e2epod.Get(f.ClientSet, pod)).WithTimeout(podInPendingStateTimeout).Should(e2epod.BeInPhase(v1.PodPending),
			^
```

It's a false positive because `e2epod.Get` is a function call which returns a function. That function gets called by `Consistently` repeatedly.

**Expected behavior**

I suspect this occurs because ginkgolinter checks whether the parameter is a function call expression. What it should do instead is check what the *type* of the expression is. Functions and channels are okay, everything else isn't.

**Environment:**
 - OS: Linux
 - Version: golangci-lint 1.53.3

**Additional context**

This can be worked around:

```patch
diff --git a/test/e2e_node/dra_test.go b/test/e2e_node/dra_test.go
index fb3da210bf2..6ea97e91a1d 100644
--- a/test/e2e_node/dra_test.go
+++ b/test/e2e_node/dra_test.go
@@ -126,7 +126,8 @@ var _ = ginkgo.Describe("[sig-node] DRA [Feature:DynamicResourceAllocation][Node
 			// TODO: Check condition or event when implemented
 			// see https://github.com/kubernetes/kubernetes/issues/118468 for details
 			ginkgo.By("check that pod is consistently in Pending state")
-			gomega.Consistently(ctx, e2epod.Get(f.ClientSet, pod)).WithTimeout(podInPendingStateTimeout).Should(e2epod.BeInPhase(v1.PodPending),
+			get := e2epod.Get(f.ClientSet, pod)
+			gomega.Consistently(ctx, get).WithTimeout(podInPendingStateTimeout).Should(e2epod.BeInPhase(v1.PodPending),
 				"Pod should be in Pending state as resource preparation time outed")
 		})
 	})
```

### PR DESCRIPTION
**Pull request by nunnatsa**
# Description
When calling a function that return a type in the async assertion (eventually/constantly) body, if this type is a function, the linter fails to recognize it and fire a warning.

This PR fixes this bug, by checking the underline types.

Fixes #91

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Added test case and related test data
- [ ] Update the functional test

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [X] I ran [golangci-lint](https://github.com/golangci/golangci-lint)

@nunnatsa

### CODE REVIEW

**Comment by nunnatsa** [comment]
@pohly, would you mind to take a look at this fix?

File: ginkgo_linter.go [hunk 1]
```diff
@@ -371,6 +368,19 @@ func checkAsyncAssertion(pass *analysis.Pass, config types.Config, expr *ast.Cal
 	return true
 }
 
+func isValidFuncCallInAsync(t gotypes.Type) bool {
```
Comment (pohly) [inline ginkgo_linter.go:371]: I was initially confused about the `FuncCall` here. This isn't checking the *function call*, it's checking the return type of the function call, is it?

Perhaps rename to `isValidAsyncValueType`?

File: ginkgo_linter.go [hunk 2]
```diff
@@ -371,6 +368,19 @@ func checkAsyncAssertion(pass *analysis.Pass, config types.Config, expr *ast.Cal
...
+	switch t.(type) {
+	// allow functions that return function or channel.
+	case *gotypes.Signature, *gotypes.Chan, *gotypes.Pointer:
```
Comment (pohly) [inline ginkgo_linter.go:374]: Nit: I find the intention easier to read when the `return true` is here instead of below.
